# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0003_auto_20180329_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecard',
            name='classes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bannercard',
            name='classes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='classes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotecard',
            name='classes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
