# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180329_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
