# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20171115_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(upload_to='card-images/%Y/')),
                ('link', models.URLField()),
                ('classes', models.CharField(max_length=200)),
                ('date_publish', models.DateField(db_index=True, verbose_name='Publish Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category', verbose_name='Categories')),
            ],
            options={
                'ordering': ['-date_publish'],
            },
        ),
    ]
