# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='date_publish',
            new_name='date',
        ),
    ]
