# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171201_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card-images/%Y/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title'),
        ),
    ]
